# 1. Introducción y configuración

## 1.1 ¿Qué es NumPy?

NumPy (Numerical Python) es la librería fundamental para el cálculo científico en Python. Permite trabajar con arreglos multidimensionales de forma eficiente, tanto en memoria como en velocidad.

## 1.2 Instalación e importación

In [1]:
# Si aún no la tienes instalada
!pip install numpy

In [2]:
# Importamos NumPy con su alias habitual
# Numpy es el nombre del paquete
# np es el alias que usaremos para referirnos a él
import numpy as np

# 2. Teoría Básica de Arrays

## 2.1 ¿Por qué usar arrays en vez de listas?


- Almacenan datos homogéneos (todos del mismo tipo).

- Operaciones vectorizadas: matemáticas en todo el array sin bucles explícitos.

- Mejor rendimiento y menor uso de memoria.

## 2.2 Creación de arrays

In [ ]:
# A partir de listas o tuplas
a = np.array([1, 2, 3, 4])
b = np.array([[1,2,3], [4,5,6]])

In [ ]:
print("Array a:\n", a)
print("Array b:\n", b)

In [ ]:
# A partir de funciones específicas
zeros = np.zeros((2,3))        # array de ceros 2×3
ones  = np.ones((3,2))         # array de unos 3×2
eye   = np.eye(4)              # matriz identidad 4×4
ar    = np.arange(0, 10, 2)    # [0,2,4,6,8]
ls    = np.linspace(0, 1, 5)   # [0.,0.25,0.5,0.75,1.]


In [ ]:
print("Array zeros:\n", zeros)
print("Array ones:\n", ones)
print("Array eye:\n", eye)
print("Array ar:\n", ar)
print("Array ls:\n", ls)

## 2.3 Atributos de los arrays (arreglos)

| Atributo   | Descripción                               |
|------------|-------------------------------------------|
| `ndim`     | Número de dimensiones                     |
| `shape`    | Tupla con el tamaño en cada dimensión     |
| `size`     | Número total de elementos                 |
| `dtype`    | Tipo de datos de los elementos            |
| `itemsize` | Bytes que ocupa cada elemento             |


In [ ]:
print(a.ndim, a.shape, a.size, a.dtype, a.itemsize)


# 3. Operaciones Básicas

NumPy aplica operaciones elemento a elemento:

In [ ]:
x = np.array([10, 20, 30])
y = np.array([1, 2, 3])

# Suma y resta
print(x + y, x - y)

# Multiplicación y división
print(x * 2, x / y)

# Funciones universales (ufuncs)
print(np.sin(x), np.exp(y))


En términos matemáticos, si

$$
\mathbf{x} = [x_1,\,x_2,\,\dots,\,x_n]
\quad\text{y}\quad
\mathbf{y} = [y_1,\,y_2,\,\dots,\,y_n]
$$

entonces:

$$
\mathbf{x} + \mathbf{y}
= [\,x_1 + y_1,\;x_2 + y_2,\;\dots,\;x_n + y_n\,]
$$

$$
\mathbf{x} - \mathbf{y}
= [\,x_1 - y_1,\;x_2 - y_2,\;\dots,\;x_n - y_n\,]
$$

Multiplicación por un escalar \(c\):

$$
c \cdot \mathbf{x}
= [\,c\,x_1,\;c\,x_2,\;\dots,\;c\,x_n\,]
$$

División elemento a elemento:

$$
\mathbf{x} \mathbin{/} \mathbf{y}
$$

Multiplicación de matrices

In [ ]:
import numpy as np

A = np.array([[1, 2],
              [3, 4]])       # Matriz 2×2

B = np.array([[5, 6],
              [7, 8]])       # Matriz 2×2

# Con np.dot
C1 = np.dot(A, B)

# Con np.matmul o @
C2 = A @ B

print(C1, C2, sep="\n\n")

# 4. Funciones útiles

| Función               | Descripción                                  |
|-----------------------|----------------------------------------------|
| `np.sum()`            | Suma de todos los elementos                  |
| `np.min(), np.max()`  | Valor mínimo y máximo                        |
| `np.mean()`           | Media aritmética                             |
| `np.std()`            | Desviación estándar                          |
| `np.reshape()`        | Cambio de forma sin copiar datos             |
| `np.flatten()`        | Aplana un array multidimensional a 1D        |
| `np.sort()`           | Ordena los elementos                         |
| `np.unique()`         | Valores únicos y conteo                      |


In [ ]:
data = np.random.randint(0, 100, size=(4,5))
print("Media:", data.mean(), "Max:", data.max(), "Desv:", data.std())

flat = data.flatten()
print("Array aplanado:", flat)

reshaped = data.reshape(5,4)
print("Array reestructurado:\n", reshaped)


# 5. Indexación y Slicing

## 5.1 Indexación básica

In [ ]:
arr = np.arange(10)        # [0,1,2,3,4,5,6,7,8,9]
print(arr[0], arr[-1])     # Primer y último elemento

mat = np.arange(9).reshape(3,3)
print(mat[1,2])            # Fila 1, columna 2


## 5.2 Slicing en 1D

La sintaxis general es arr[start:stop:step].

In [ ]:
print(arr[2:8])       # [2,3,4,5,6,7]
print(arr[:5])        # [0..4]
print(arr[5:])        # [5..9]
print(arr[::2])       # Saltos de 2 → [0,2,4,6,8]
print(arr[::-1])      # Invertido → [9,8,7,6,5,4,3,2,1,0]

## 5.3 Slicing en 2D

In [ ]:
# Seleccionar submatriz de filas 0-1 y columnas 1-2
print(mat[0:2, 1:3])

# Todas las filas, columna 0
print(mat[:, 0])

# Filas 1 y 2, todas las columnas
print(mat[1:3, :])


## 5.4 Máscara booleana

In [ ]:
mask = arr % 2 == 0
print(arr[mask])      # Filtra los pares

# Combinando condiciones
print(arr[(arr>3) & (arr<8)])  # [4,5,6,7]


# Práctica

1. Crea un array con 10 edades aleatorias y calcula la media, mínima y máxima.

2. Genera un array 5×5 con valores aleatorios entre 0 y 1; extrae su fila central.

3. Dado un array de 20 enteros, reemplaza los valores impares por -1.

4. Usa reshape para convertir un array de 16 elementos en una matriz 4×4 y muestra su diagonal principal.

In [63]:
# Escribe aquí tu código
import numpy as np
edades = np.random.randint(0, 100,size=(1,10))
print(edades)
media= np.mean(edades)
minimo= edades.min()
print(minimo)

maximo= np.max(edades)

print(maximo)

print("La media es:",media,"la edad minima es:",minimo,"y la edad maxima:",maximo)
np.min(edades), np.max(edades)

#ej2
array2 = np.random.rand(5,5)
print(array2)
arraymodificado=array2[2]
arraymodificado

#ej3
array3=np.random.randint(100,size=20)
array3
array3modificado=array3.copy()
array3modificado[array3modificado % 2 !=0] = -1
print(f'Array original: {array3} \n'
      f'Array cambiado:  {array3modificado}')


[[76 64 29 96  7  8 33 12 14 99]]
7
99
La media es: 43.8 la edad minima es: 7 y la edad maxima: 99
[[1.15272744e-01 6.51625716e-01 6.92538356e-01 7.25940634e-01
  2.16700180e-02]
 [9.08957570e-01 1.59058859e-01 4.35713844e-01 2.62151708e-06
  6.12315063e-01]
 [2.59350155e-01 5.12554307e-01 4.57034110e-01 1.23904692e-03
  3.36628235e-01]
 [9.19585090e-01 9.84377459e-01 4.05850140e-01 5.28302301e-01
  8.15909807e-01]
 [6.84579730e-01 7.18111295e-01 8.32522397e-02 3.47295638e-01
  6.98929036e-01]]
Array original: [50 96 40 85 19 30 67 45 32 98 13 38 56 52 79 77 64 96 19 20] 
Array cambiado:  [50 96 40 -1 -1 30 -1 -1 32 98 -1 38 56 52 -1 -1 64 96 -1 20]


In [38]:
#ej3
array3=np.random.randint(100,size=20)

array3modificado=array3.copy()

for index in range(len(array3modificado)):
  if array3modificado[index] % 2 !=0:
    array3modificado[index] = -1
print(f'Array original: {array3} \n'
      f'Array cambiado:  {array3modificado}')

for i, elemento in enumerate(array3modificado):
  if elemento %2 !=0:
    array3modificado[index]= -1

print(f'Array original:{array3}\n
f'Array modificado: {Array modificado}')

Array original: [67 90 10 39 57 35 17 42 86 92  2 13 31 35 14 75 71 32 61 82] 
Array cambiado:  [-1 90 10 -1 -1 -1 -1 42 86 92  2 -1 -1 -1 14 -1 -1 32 -1 82]


In [65]:

#ej 4
array4= np.arange(0,16)
print(array4)

array4x4=array4.reshape(4,4)
print(array4x4)

diagonal=[]
for i in range(len(array4x4)):
    diagonal.append(array4x4[i,i])

print(diagonal)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[np.int64(0), np.int64(5), np.int64(10), np.int64(15)]


Crea dos arrays:

- A de forma (3, 1) con valores aleatorios de 0 a 10.

- B de forma (1, 4) con valores aleatorios de 0 a 10.

Suma A + B y observa la forma del resultado.

Multiplica cada fila de la matriz de resultados por un vector [1, 2, 3, 4] usando broadcasting.

In [72]:
A= np.random.randint(0,11,size=(3,1))
B= np.random.randint(0,11,size=(1,4))

suma=A+B
print(f'matriz A:{A}\n 'f'matrizB:{B} \n' f'A+B{suma}')


vector= np.array([1,2,3,4])

mult=suma * vector
print(mult)

matriz A:[[6]
 [0]
 [1]]
 matrizB:[[3 2 3 3]] 
A+B[[9 8 9 9]
 [3 2 3 3]
 [4 3 4 4]]
[[ 9 16 27 36]
 [ 3  4  9 12]
 [ 4  6 12 16]]


Slicing en 2D (submatriz interior y rotación)

- Genera un array 6×6 con valores del 1 al 36 (por ejemplo con arange y reshape).

- Usa slicing para extraer la submatriz interior 4×4 (eliminas la primera y la última fila y columna).

- A continuación, aplica un slicing con paso negativo para rotar esa submatriz 180°.

- Imprime la matriz original, la submatriz interior y la submatriz rotada.


In [93]:

A66=np.arange(1,37)
A66=A66.reshape(6,6)

print(A66)

#slicing

print(A66[0:4, 0:4])

rotada= A66[::-1,::-1]
print(rotada)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
[[ 1  2  3  4]
 [ 7  8  9 10]
 [13 14 15 16]
 [19 20 21 22]]
[[36 35 34 33 32 31]
 [30 29 28 27 26 25]
 [24 23 22 21 20 19]
 [18 17 16 15 14 13]
 [12 11 10  9  8  7]
 [ 6  5  4  3  2  1]]


Con una matriz 5×5 de valores aleatorios:

- Calcula la media, mediana y desviación estándar global.

- Obtén la suma de cada columna y de cada fila.

Aplica np.sin y np.exp elemento a elemento y compara resultados.

In [110]:
mat=np.random.uniform(100,size=(5,5))
mat


mat1=mat.flatten()
mat1

mat1ord=np.sort(mat1)
mat1ord

mediana= mat1ord[size(mat1ord)/2]


NameError: name 'size' is not defined

Genera dos matrices cuadradas X y Y de tamaño 3×3.

Calcula:

- Su producto matricial (np.dot o @).

- El determinante de X.

- El inverso de Y y comprueba que Y @ Y_inv da la identidad.

Resuelve el sistema lineal X · v = b para un vector b dado.

In [113]:
X=np.random.rand(3,3)
Y=np.random.rand(3,3)

prod= X @ Y

det_X= np.linalg.det(X)

inv_Y= np.linalg.inv(Y)

identidad= np.eye(3)

print(np.dot(Y, inv_Y))

if np.allclose(Y@inv_Y, identidad):
  print('Lo es')

[[ 1.00000000e+00  2.37837987e-16 -4.21278911e-16]
 [ 1.29650910e-15  1.00000000e+00 -2.26418542e-16]
 [ 4.05306174e-16 -2.24661206e-15  1.00000000e+00]]
Lo es


Generar 10 000 muestras de una distribución normal con media 0 y desviación estándar 1.

Mostrar un histograma normalizado de esas muestras con 50 bins.

Extra: Superponer la curva teórica de la densidad de la N(0,1) sobre el histograma